name: Publish tag to PyPI
on:
  release:
    types: [published]

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:

  build_sdist:
    name: Build source dist
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build sdist
        run: |
          python3 setup.py sdist
      - uses: actions/upload-artifact@v4
        with:
          name: source-dist
          path: ./dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-latest]
    env:
      CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
      MACOSX_DEPLOYMENT_TARGET: "11.0"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          # configure cibuildwheel to build native archs ('auto'), and some
          # emulated ones
          CIBW_ARCHS_LINUX: auto aarch64 ppc64le s390x

      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}-wheels
          path: ./wheelhouse/*.whl

  publish:
    name: PyPI publish
    needs: ['build_sdist', 'build_wheels']
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ubuntu-20.04-wheels
          path: artifacts/linux
      - uses: actions/download-artifact@v4
        with:
          name: windows-2019-wheels
          path: artifacts/windows
      - uses: actions/download-artifact@v4
        with:
          name: macos-latest-wheels
          path: artifacts/macos
      - uses: actions/download-artifact@v4
        with:
          name: source-dist
          path: artifacts/sdist
      - name: unify wheel structure
        run: |
          mkdir dist
          cp -R artifacts/windows/* dist
          cp -R artifacts/linux/* dist
          cp -R artifacts/macos/* dist
          cp -R artifacts/sdist/* dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
